# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS App
  pod 'Alamofire'

  target 'IOS AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS AppUITests' do
    # Pods for testing
  end

end
